### ISSUE TITLE
Research cool open source project repos and find useful tags for our case

### ISSUE THREAD

**Issue by ergun1017** [bounswe/bounswe2018group2#1]

**Comment by nilsupamuk** [comment]
I liked the structure of their page a lot :+1:  https://github.com/bounswe/bounswe2016group2/wiki  
and their labeling system could be really helpfull for us in the future:  https://github.com/bounswe/bounswe2016group2/wiki/Labeling-System

**Comment by huriozdmr** [comment]
My suggestion for possible tags:  waiting-response,  type,  pending, needs-decision, enhancement

**Comment by harun-eren-2015400072** [comment]
my suggestion for possible tags: effective use of "status-"  and "type-" tags as in https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63 , "backend" and "frontend"

**Comment by aliturgutalp** [comment]
I am closing the issue since the task is over
