### ISSUE TITLE
Setup node and npm to run react

### ISSUE THREAD

**Issue by huriozdmr** [bounswe/bounswe2018group2#111]
Complete requirements to start front end part of the project.

**Comment by ergunsh** [comment]
hey hey! I've opened a PR for this: https://github.com/bounswe/bounswe2018group2/pull/110. If you need any help installing npm and node, feel free to ask. Also, I can explain the structure and setup the project tomorrow at the meeting.

**Comment by huriozdmr** [comment]
Thanks! I saw your guide, I follow the steps you mentioned there :)

**Comment by ergunsh** [comment]
I'm closing the issue, feel free to reopen and ask questions :)
