### ISSUE TITLE
Deploy api

### ISSUE THREAD

**Issue by ergunsh** [bounswe/bounswe2018group2#112]
We need to decide on where to deploy the api.

Then, we can set up CI/CD environments.

**Comment by ergunsh** [comment]
I think, we need an AWS account; is there anyone having free tier things? @aliturgutalp @bartuinceQR @nilsupamuk 

We need this issue to be resolved ASAP to integrate frontend - android apps with api.

**Comment by aliturgutalp** [comment]
@ergunsh had some problems with billing on aws. I will inform you if anything changes

**Comment by ergunsh** [comment]
We can also use digital ocean if you want; it has 50$ credit in github student pack. I've exhausted it also 😂
