### ISSUE TITLE
Create a wiki page that describes yourself and update your links on both README.md and sidebar

### ISSUE THREAD

**Issue by ergun1017** [bounswe/bounswe2018group2#3]
After you have created a new page and filled that page with your personal information, you can update your links on README.md by clicking the file and clicking edit (something like this: ✏️ 😄 ) and you can update the sidebar links on the wiki by clicking the same icon on the sidebar.

**Comment by aliturgutalp** [comment]
Done and done 👍

**Comment by bartuinceQR** [comment]
Done :cowboy_hat_face:

**Comment by huriozdmr** [comment]
done 👍

**Comment by harun-eren-2015400072** [comment]
done :v:

**Comment by nilsupamuk** [comment]
Done 🎉

**Comment by sukrugultop** [comment]
done 👍

**Comment by fatihmehmetkiris** [comment]
done

**Comment by zekitel** [comment]
done

**Comment by aliturgutalp** [comment]
You can see the related issue [here](https://github.com/bounswe/bounswe2018group2/issues/7) about the last person's info page
