### ISSUE TITLE
Determine time intervals in Project Plan

### ISSUE THREAD

**Issue by harun-eren-2015400072** [bounswe/bounswe2018group2#34]
We've created first draft of project plan on Project Libre in the online meeting. We've decided milestones and tasks. But the time intervals of tasks and milestones were not determined yet.  Can you update the project plan by determining the time invervals?

**Comment by zekitel** [comment]
please, update the project plan
[the draft of the high level project plan in the pdf format ](https://drive.google.com/file/d/1BBVXTlNhXMAPzI8_Zvg7E56ygwDmIqcP/view?usp=sharing)
[project-libre file is here](https://drive.google.com/file/d/1Fi6fpIxltnA-Z8M35LySj_D27CmZrF00/view?usp=sharing)

**Comment by mericturan** [comment]
Guys,

You keep assigning me to your issues. Please don’t.

Regards,
Meriç Turan

**Comment by nilsupamuk** [comment]
It is done after the meeting on 25.02.2018.
