### ISSUE TITLE
Improve mock-ups according to feedback

### ISSUE THREAD

**Issue by harun-eren-2015400072** [bounswe/bounswe2018group2#52]
I'll improve the mock-ups according to feedback & suggestions, mostly I will convert "lorem ipsum" parts to real data.

**Comment by ergun1017** [comment]
Any update on this? @harun-eren-2015400072

**Comment by harun-eren-2015400072** [comment]
I close the issue without expecting feedback, since I've not worked systematically, just found something that needs to be change and changed it according to given suggestions. Then Bartu improved the mock-ups comprehensively, including the parts I've changed.
