### ISSUE TITLE
Improve requirements page according to feedback

### ISSUE THREAD

**Issue by aliturgutalp** [bounswe/bounswe2018group2#53]

**Comment by ergun1017** [comment]
Any update on this? @aliturgutalp

**Comment by aliturgutalp** [comment]
Hey, I updated functional requirements and I think we are good to go for now. So I am closing the issue

**Comment by ergun1017** [comment]
pşş, you can add `needs feedback` label before closing an issue 😄

Read more: https://github.com/bounswe/bounswe2018group2/wiki/Contribution-Guide-(Draft)#resolving-an-issue
