### ISSUE TITLE
Revamp web & mobile mockups

### ISSUE THREAD

**Issue by ergunsh** [bounswe/bounswe2018group2#56]

**Comment by ergun1017** [comment]
I think, Bartu is completed all mockups; they look great, we can give feedback in here 🎉 🎉 

[Mobile mockups](https://github.com/bounswe/bounswe2018group2/wiki/Mobile-mockups)
[Web mockups](https://github.com/bounswe/bounswe2018group2/wiki/Web-Mockups)

**Comment by ergun1017** [comment]
About mobile mockups:

I liked the design, but; I think, we can change things related to full time kinda job things to one time only job. (Software Engineer @Linkedin -> Create a mobile app @hasanabi)

Web mockups also great 🎉
