### ISSUE TITLE
Add Meeting Notes #8

### ISSUE THREAD

**Issue by huriozdmr** [bounswe/bounswe2018group2#62]

**Comment by ergun1017** [comment]
Umm, wouldn't we have an issue about finding a name about our platform 🤔 @huriozdmr

**Comment by harun-eren-2015400072** [comment]
In  #7th meeting notes, it is said that the team will discuss about the name of the project at #8th meeting.  What did you discuss about it? Did anyone come with any idea? :eyes:

**Comment by huriozdmr** [comment]
I created a new issue about name for project. You can make a suggestion.
