### ISSUE TITLE
Discuss about a name for our project

### ISSUE THREAD

**Issue by huriozdmr** [bounswe/bounswe2018group2#65]
@bounswe/bounswe2018group2  Please leave comment about a new name suggestion for our project

**Comment by ergun1017** [comment]
UpWork, SparkleWork, Sparklancer 😄

**Comment by bartuinceQR** [comment]
Yousoro, Freesaber, Work Candy

**Comment by zekitel** [comment]
WorkHub makes sense 👌

**Comment by ergunsh** [comment]
Sooo, what did we choose? 😅

**Comment by ergunsh** [comment]
Halo! @huriozdmr @bartuinceQR @aliturgutalp @zekitel @harun-eren-2015400072 @sukrugultop @nilsupamuk

**Comment by ergunsh** [comment]
Up for the new semester 😂 

Workhub?

**Comment by ergunsh** [comment]
Workhub 🎉
