### ISSUE TITLE
Non functional requirements need revision

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group2#91]
Some of your non functional requirements need revision.

ie. if your system needs to support CAPTCHA. this is functional. 

The following is a strange one. Are other requirements not going to be tested? This does not seem right. 

3.6.2 The annotations shall be tested by test team to ensure that they work correctly.

If you want to talk about testing, you can state the coverage of tests that are expected.

**Comment by aliturgutalp** [comment]
Necessary changes have been applied. Thank you for your input. In the future we must be a lot more careful.
